[versions]
adventure = "5.2.0"
cloud-minecraft = "2.0.0"
flyway = "13.2.0"

[libraries]
# Platforms
platform-paper = { module = "io.papermc.paper:paper-api", version = "26.2.build.+" }
platform-velocity = { module = "com.velocitypowered:velocity-api", version = "4.0.0" }

# Storage
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "7.1.0" }
storage-mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version = "3.5.10" }
storage-sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.53.2.1" }

# Cloud
cloud-jda = { module = "org.incendo:cloud-jda6", version = "1.0.0-SNAPSHOT" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud-minecraft" }
cloud-translations = { module = "org.incendo:cloud-translations-core", version = "1.0.0-beta.2" }
cloud-velocity = { module = "org.incendo:cloud-velocity", version.ref = "cloud-minecraft" }

# Adventure
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }

# Misc
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.4" }
dazzleconf = { module = "space.arim.dazzleconf:dazzleconf-toml", version = "2.0.0-M2" }
gson = { module = "com.google.code.gson:gson", version = "2.14.0" }
jda = { module = "net.dv8tion:JDA", version = "6.5.0" }
slf4j = { module = "org.slf4j:slf4j-api", version = "2.0.16" }

[plugins]
versions = { id = "io.github.ben-manes.versions", version = "0.59.0" }